name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with unittest
      run: |
        python -m unittest discover tests
    - name: Update Coverage Badge
      # GitHub actions: default branch variable
      # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: we-cli/coverage-badge-action@main
